---
# Config nginx with TLS

    - name: Apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Copy nginx config file
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
        state: present

    - name: Enable configuration
      ansible.builtin.file:
        src: /etc/nginx-available/default
        dest: /etc/sites-enabled/default
        state: link

    - name: Copy index.html
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /url/share/nginx/html/index.html
        mode: 0644
